import type { Metadata } from 'next';
import { ChakraProviders } from 'ui';
import './globals.css';
import { Navbar } from '@/navigation/Navbar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body>
                <ChakraProviders>
                    <Navbar />
                    {children}
                </ChakraProviders>
            </body>
        </html>
    );
}
