service: trpc-cv-backend
frameworkVersion: '3'

useDotenv: true

provider:
    name: aws
    runtime: nodejs14.x
    httpApi:
        cors: true
    environment:
        SLACK_INTERNAL_TOKEN: ${env:SLACK_INTERNAL_TOKEN}

functions:
    http-api:
        handler: dist/server.handler
        events:
            - httpApi:
                  path: '*'
                  method: '*'

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
