service: trpc-menno-cv
frameworkVersion: '3'
region: eu-north-1

useDotenv: true

provider:
    name: aws
    runtime: nodejs14.x
    environment:
        SLACK_INTERNAL_TOKEN: ${env:SLACK_INTERNAL_TOKEN}

functions:
    http-api:
        handler: src/app.handler
        events:
            - httpApi: '*'
    rest-api:
        handler: src/app.handler
        events:
            - http:
                  path: /{proxy+}
                  method: any

plugins:
    - serverless-esbuild
    - serverless-offline

custom:
    esbuild:
        platform: neutral
        external: '@slack/web-api'
